[Startup]
AppName=AIBO Entertainment Player Ver.2.0
ProductGUID=DC40FA5F-B57D-4B32-9A72-FA8CA71DB3BA
CompanyName=Sony Corporation
ErrorReportURL=http://www.installshield.com/isetup/ProErrorCentral.asp?ErrorCode=%d : 0x%x&ErrorInfo=%s
MediaFormat=1
LogMode=1
Skin=setup.isn
Resource=_Setup.dll
SmallProgress=N
SplashTime=5
CheckMD5=Y
CmdLine=
ShowPasswordDialog=N
EngineVersion=10.1.0.238
EngineBinding=0
[Languages]
Default=0x0009
count=2
key0=0x0009
key1=0x0011
