[Startup]
AppName=WLANManager
ProductGUID=5796280D-4724-439F-A6D7-B397D575AE8A
CompanyName=Sony Corporation
ErrorReportURL=http://www.installshield.com/isetup/ProErrorCentral.asp?ErrorCode=%d : 0x%x&ErrorInfo=%s
MediaFormat=1
LogMode=1
Resource=_Setup.dll
SmallProgress=N
SplashTime=5
CheckMD5=Y
CmdLine=
ShowPasswordDialog=N
EngineVersion=10.1.0.238
EngineBinding=0
[Languages]
Default=0x0009
count=2
key0=0x0009
key1=0x0011
